### ISSUE TITLE
Bluetooth Beacon Interactor crashes on discovery of estimote dev kit beacons

### ISSUE THREAD

**Issue by matthiasg** [andijakl/universal-beacon#2]
it starts listing , then crashes while its doing that. what input would you need to debug ?

**Comment by andijakl** [comment]
Do you know which type of beacon is nearby? Is it Eddystone or something else? Do you have access to an Android phone or an iPhone with a Beacon scanner app that shows the raw data that the beacon transmits?

**Comment by andijakl** [comment]
In crash reports of the live app, I've seen that it can happen that the received beacon advertisement is null and the app was therefore crashing. I've fixed that in the source code on GitHub and will push an update to the store app during the next few days. The library will now ignore beacon updates that are actually null.

I guess that should fix the issue you've discovered, otherwise please comment with more details! Thanks for reporting!
